### ISSUE TITLE
Add Python, Ruby, C#, Java, Rust transpile support

### ISSUE THREAD

**Issue by Dandigit** [Dandigit/braindigit#4]
Aiming for an ultra flexible Brainfuck language tool. Tracking the progress of future branches: `python-transpile ruby-transpile csharp-transpile java-transpile rust-transpile`.

**Comment by Dandigit** [comment]
I'll start with Python. [braindigit/python-transpile](https://github.com/Dandigit/braindigit/tree/python-transpile)

**Comment by Dandigit** [comment]
Python transpiler now open for review in #6: Python transpiling.

**Comment by Dandigit** [comment]
#6 merged. Will move on to Ruby.

**Comment by Dandigit** [comment]
Initial commit made: [braindigit/ruby-transpile](https://github.com/Dandigit/braindigit/tree/ruby-transpile)

**Comment by Dandigit** [comment]
#9: Ruby transpiling created and merged. node.js next.

**Comment by Dandigit** [comment]
Hmm.. on second thought, I might skip JS. C# now.

**Comment by SimpleBinary** [comment]
@Dandigit Can you transpile Python to Brainlang?

**Comment by Dandigit** [comment]
@SimpleBinary No, but it is technically possible as Brainfuck is Turing complete.

**Comment by BonfireScratch** [comment]
@Dandigit May I open an issue named "Difficulty of understanding that source code"? How can you understand it? Why does C and C++ have an int instead of a nice and clear DEF OR FUNCTION OR THE THINGS THAT BRAINFUCK DOES?
